# Configuração de Deploy para DOMcloud
# Sistema de Gerenciamento de Pátio de Veículos

# Repositório GitHub (substitua pelo seu)
source: https://github.com/julioborgesigt/patio-veiculos

# Configurações de runtime
features:
  - node lts  # Usa a versão LTS mais recente do Node.js

# Configuração do Passenger (servidor de aplicação)
passenger:
  enabled: "on"
  # app.js na raiz do projeto carrega dist/index.js
  app_start_command: node app.js
  
  # Variáveis de ambiente
  env_var_list:
    # === BANCO DE DADOS ===
    # Credenciais separadas (mais compatível com DOMcloud)
    - DB_HOST=localhost
    - DB_USER=patioiguatu
    - DB_PASSWORD=8TbEh)13+D8_sq8zAX
    - DB_NAME=patioiguatu_patio_user
    # DATABASE_URL será construída automaticamente pelo script de migração
    - DATABASE_URL=mysql://patioiguatu:8TbEh%2913%2BD8_sq8zAX@localhost/patioiguatu_patio_user
    
    # === SEGURANÇA ===
    # IMPORTANTE: Gere uma chave aleatória segura
    # Execute: node -e "console.log(require('crypto').randomBytes(32).toString('hex'))"
    - JWT_SECRET=pSTnJ1H6RGYc8zYKVieTxeHr2L8Jbdyv
    
    # === API PLACAS ===
    # Token da API Placas para consulta de dados veiculares
    - API_PLACAS_TOKEN=88c5130c5f73f6c829ed04a1e991eee4
    
    # === AMBIENTE ===
    - NODE_ENV=production
    
    # === AUTENTICAÇÃO MANUS (OPCIONAL) ===
    # Estas variáveis são do sistema Manus e não funcionarão fora da plataforma
    # Você pode removê-las ou adicionar DISABLE_AUTH=true para desabilitar autenticação
    # - DISABLE_AUTH=true

# Comandos executados durante o deploy
commands:
  # 1. Garantir que pnpm está disponível (via corepack que já está instalado)
  - corepack enable
  
  # 2. Instalar dependências do projeto
  - pnpm install
  
  # 3. Executar build do projeto (compila TypeScript e prepara frontend)
  - pnpm build
  
  # 4. Executar migrações do banco de dados (cria tabelas)
  - node scripts/migrate-production.mjs
  
  # 5. Criar diretório temporário e arquivo de restart (necessário para Passenger)
  - mkdir -p tmp && touch tmp/restart.txt

# Nginx (configuração adicional se necessário)
nginx:
  # Configuração de proxy reverso já está no tutorial
  # Adicione aqui se precisar de configurações extras
