source: https://github.com/julioborgesigt/patio-veiculos

features:
  - node lts

passenger:
  enabled: "on"
  app_start_command: node dist/index.js

  env_var_list:
    - DB_HOST=localhost
    - DB_USER=patioiguatu
    - DB_PASSWORD=8TbEh)13+D8_sq8zAX
    - DB_NAME=patioiguatu_patio_user
    - DATABASE_URL=mysql://patioiguatu:8TbEh%2913%2BD8_sq8zAX@localhost/patioiguatu_patio_user
    - JWT_SECRET=pSTnJ1H6RGYc8zYKVieTxeHr2L8Jbdyv
    - API_PLACAS_TOKEN=88c5130c5f73f6c829ed04a1e991eee4
    - NODE_ENV=production

commands:
  - corepack enable
  - pnpm install
  - pnpm build
  - node scripts/migrate-production.mjs
  - mkdir -p tmp && touch tmp/restart.txt
